version: 2
updates:
  - directory: "/"
    package-ecosystem: "npm"
    schedule:
      interval: "daily"
    assignees:
      - "Timeraa"
      - "TheDropX"
    commit-message:
      prefix: "🔼"
      prefix-development: "🔼"
    labels:
      - "dependencies"
    open-pull-requests-limit: 15
    #Should be removed/updated when nuxt + vue support webpack 5
    ignore:
      - dependency-name: "sass-loader"
        version: "^11"
