name: CD Docker
on:
  workflow_run:
    workflows: ["CI"]
    branches:
      - stable
      - main
    types:
      - completed
jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'PreMiD'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3.0.0
        with:
          python-version: "3.x"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ steps.extract_branch.outputs.branch }}
